[IO]
  checkpointFileNumber = 0
  plotFileNumber = 0

[Grid]
  nblockx = 30
  nblocky = 40
  nrefs = 10000
  lrefine_min = 1
  lrefine_max = 1
  xmin = -1.5
  xmax = 1.5
 
[IncompNS]
  ins_dtSpec = 3.125e-6

[Driver]
  restart = false
  nend = 10000000
  tmax = 5
  dtinit = 3.125e-6
  dtmax = 3.125e-6
