[IO-RESTART]
  restart = false
  nend = 10000000
  tmax = 5
  checkpointFileIntervalTime = 1.0
  checkpointFileIntervalStep = 0
  plotFileIntervalTime = 0.1
  plotFileIntervalStep = 0
  plot_var_1 = "pres"
  plot_var_2 = "velx"
  plot_var_3 = "vely"
  plot_var_4 = "dfun"
  plot_var_5 = "visc"
  plot_var_6 = "rhoc"

[FLUID-PROPERTIES]
  ins_invReynolds = 0.0285
  ins_gravY = -1.0
  mph_rhoGas = 0.001
  mph_muGas = 0.01
  mph_iPropSmear = 1.0
  mph_invWeber = 0.008

[SCALES]
  length = 0.5
  time = 0.714
  velocity = 0.7
