# Top level configuration file for Rising Bubble problem

[Simulation]
  sim_bubbleRadius = 0.5

[Logfile]
  run_comment = "Rising Bubble problem"
  log_file = "INS_Rising_Bubble.log"

[IO]
  basenm = "INS_Rising_Bubble_"

[Grid]
  geometry = "cartesian"
  xmin = -1.0
  xmax = 1.0
  ymin = -1.0
  ymax = 3.0
  xl_boundary_type = "slip_ins"
  xr_boundary_type = "slip_ins"
  yl_boundary_type = "noslip_ins"
  yr_boundary_type = "outflow_ins"
  zl_boundary_type = "noslip_ins"
  zr_boundary_type = "noslip_ins"
  gr_amrexMG_composite_solve = true
  gr_amrexMG_Tol = 1e-13
  gr_amrexMG_max_iter = 200

[Driver]
  tstep_change_factor = 1.0

[IncompNS]
  ins_cflFlg = 0
  ins_cfl = 0.05
  ins_sigma = 0.05
  ins_pressureCorrect = false
  ins_intSchm = 1
  ins_advSchm = 105

[Multiphase]
  mph_lsIt = 2
