[Grid]
  nblockx = 40
  nblocky = 80
  nrefs = 10000
  lrefine_min = 1
  lrefine_max = 1

[IncompNS]
  ins_dtSpec = 7.8125e-7

[IO]
  ignoreForcedPlot = true

[Driver]
  wall_clock_time_limit = 7200
  dtinit = 7.8125e-7
  dtmax = 7.8125e-7
