# Top level configuration file for Evaporating Bubble problem

[Simulation]
  sim_bubbleRadius = 0.25
  sim_outletBuffer = 1.0
  sim_outletGrowthRate = 4.0

[Logfile]
  run_comment = "Evaporating Bubble problem"
  log_file = "INS_Evaporating_Bubble.log"

[IO]
  basenm = "INS_Evaporating_Bubble_"
  checkpointFileIntervalTime = 1.0
  checkpointFileIntervalStep = 0
  plotFileIntervalTime = 0.1
  plotFileIntervalStep = 0
  plot_var_1 = "pres"
  plot_var_2 = "velx"
  plot_var_3 = "vely"
  plot_var_4 = "dfun"
  plot_var_5 = "rhoc"
  plot_var_6 = "temp"
  plot_var_7 = "dust"
  plot_var_8 = "mflx"
  ignoreForcedPlot = true
  checkpointFileNumber = 0
  plotFileNumber = 0

[Grid]
  geometry = "cartesian"
  xmin = -0.75
  xmax = 0.75
  ymin = -0.5
  ymax = 2.5
  zmin = -0.75
  zmax = 0.75
  xl_boundary_type = "noslip_ins"
  xr_boundary_type = "noslip_ins"
  yl_boundary_type = "noslip_ins"
  yr_boundary_type = "outflow_ins"
  zl_boundary_type = "noslip_ins"
  zr_boundary_type = "noslip_ins"
  gr_amrexMG_composite_solve = true
  gr_amrexMG_Tol = 1e-13
  gr_amrexMG_max_iter = 200
  nblockx = 6
  nblocky = 12
  nrefs = 10000
  lrefine_min = 1
  lrefine_max = 1

[Driver]
  restart = false
  wall_clock_time_limit = 7000
  dtinit = 0.25e-4
  dtmax = 0.25e-4
  tstep_change_factor = 1.0
  nend = 10000000
  tmax = 10

[IncompNS]
  ins_cflFlg = 0
  ins_cfl = 0.05
  ins_sigma = 0.05
  ins_pressureCorrect = false
  ins_intSchm = 2
  ins_advSchm = 105
  ins_invReynolds = 5e-3
  ins_gravY = -1.0
  ins_dtSpec = 0.25e-4

[Multiphase]
  mph_lsIt = 2
  mph_rhoGas = 1.2e-3
  mph_muGas = 2.5e-4
  mph_iPropSmear = 1.0
  mph_invWeber = 2e-2
  mph_Stefan = 4e-3
  mph_thcoGas = 2e-1
  mph_CpGas = 7e-1

[HeatAD]
  ht_Prandtl = 7.0
