# Top level configuration file for Pool Boiling problem
[Grid]
  ymax = 24.0
  nblocky = 72

[Simulation]
  sim_outletBuffer = 1.0

[Driver]
  restart = true

[IO]
  checkpointFileNumber = 17
  plotFileNumber = 156
