[Driver]
  restart = false
  nend = 10000000
  tmax = 5

[IO]
  checkpointFileIntervalTime = 1.0
  checkpointFileIntervalStep = 0
  plotFileIntervalTime = 0.1
  plotFileIntervalStep = 0
  plot_var_1 = "pres"
  plot_var_2 = "velx"
  plot_var_3 = "vely"
  plot_var_4 = "dfun"
  plot_var_5 = "visc"
  plot_var_6 = "rhoc"

[IncompNS]
  ins_invReynolds = 0.0285
  ins_gravY = -1.0

[Simulation]
  sim_lengthScaleMeters = 0.5
  sim_timeScaleSeconds = 0.714

[Multiphase]
  mph_rhoGas = 0.1
  mph_muGas = 0.1
  mph_iPropSmear = 1.0
  mph_invWeber = 0.1
