[Fluid-Properties]
  ins_invReynolds = 0.00460
  ins_gravY = -1.0
  mph_rhoGas = 1.21e-3
  mph_muGas = 2.45e-4
  mph_iPropSmear = 1.0
  mph_invWeber = 0.0083
  
[AMR-Resolution]
  nblockx = 3
  nblocky = 6
  nrefs = 10000
  lrefine_min = 1
  lrefine_max = 1

[Temporal-Stability]
  ins_dtSpec = 1.0e-4
  dtinit = 1.0e-4
  dtmax = 1.0e-4
