# Top level configuration file for Rising Bubble problem

[Bubble]
  sim_bubbleRadius = 0.25

[Domain]
  geometry = "cartesian"
  xmin = -0.5
  xmax = 0.5
  ymin = -0.5
  ymax = 1.5

[Boundary-Conditions] 
  xl_boundary_type = "noslip_ins"
  xr_boundary_type = "noslip_ins"
  yl_boundary_type = "noslip_ins"
  yr_boundary_type = "noslip_ins"
  zl_boundary_type = "noslip_ins"
  zr_boundary_type = "noslip_ins"

[Run-Information]  
  run_comment = "Rising Bubble problem"
  log_file = "INS_Rising_Bubble.log"
  basenm = "INS_Rising_Bubble_"

[Temporal-Stability]
  ins_cflFlg = 1
  ins_cfl = 0.05
  ins_sigma = 0.05
  tstep_change_factor = 1.0
  ins_pressureCorrect = false

[IO-Restart]
  restart = false
  nend = 10000000
  tmax = 10 
  checkpointFileIntervalTime = 1.0
  checkpointFileIntervalStep = 0
  plotFileIntervalTime = 1.0
  plotFileIntervalStep = 0
  plot_var_1 = "pres"
  plot_var_2 = "velx"
  plot_var_3 = "vely"
  plot_var_4 = "dfun"
 
[Poisson-Solver]
  gr_amrexMG_composite_solve = true
  gr_amrexMG_Tol = 1e-13
  gr_amrexMG_max_iter = 200
