# Top level configuration file for Rising Bubble problem

[BUBBLE]
  sim_bubbleRadius = 0.5

[DOMAIN]
  geometry = "cartesian"
  xmin = -1.0
  xmax = 1.0
  ymin = -1.0
  ymax = 3.0

[BOUNDARY-CONDITIONS] 
  xl_boundary_type = "noslip_ins"
  xr_boundary_type = "noslip_ins"
  yl_boundary_type = "noslip_ins"
  yr_boundary_type = "noslip_ins"
  zl_boundary_type = "noslip_ins"
  zr_boundary_type = "noslip_ins"

[RUN-INFORMATION]  
  run_comment = "Rising Bubble problem"
  log_file = "INS_Rising_Bubble.log"
  basenm = "INS_Rising_Bubble_"

[TEMPORAL-STABILITY]
  ins_cflFlg = 1
  ins_cfl = 0.05
  ins_sigma = 0.05
  tstep_change_factor = 1.0
  ins_pressureCorrect = false

[POISSON-SOLVER] 
  gr_amrexMG_composite_solve = true
  gr_amrexMG_Tol = 1e-13
  gr_amrexMG_max_iter = 200
