# Input file to set runtime parameters

[Logfile]
  run_comment = "Flow Boiling problem"
  log_file = "INS_Flow_Boiling.log"

[Timers]
  CSVSummaryAllProcs = true

[Heater]
  sim_heaterName = "flow_boiling"
  sim_numHeaters = 2
  sim_nucSeedRadius = 0.1
  sim_heaterShowInfo = false

[Heater.0001]
  dim = 1
  xmin = -20.0
  xmax = -5.0
  ymin = 0.0
  ymax = 1e-13
  zmin = -2.5
  zmax = 2.5
  wallTemp = 2.0
  advAngle = 90.0
  rcdAngle = 45.0
  velContact = 0.2
  nucWaitTime = 0.4
  numSites = 90
  nucSeedRadius = 0.1

[Heater.0002]
  dim = 1
  xmin = 5.0
  xmax = 20.0
  ymin = 0.0
  ymax = 1e-13
  zmin = -2.5
  zmax = 2.5
  wallTemp = 1.0
  advAngle = 90.0
  rcdAngle = 45.0
  velContact = 0.2
  nucWaitTime = 0.4
  numSites = 70
  nucSeedRadius = 0.1

[Grid]
  geometry = "cartesian"
  xmin = -25.0
  xmax = 25.0
  ymin = 0.0
  ymax = 5.0
  xl_boundary_type = "inflow_ins"
  xr_boundary_type = "outflow_ins"
  yl_boundary_type = "noslip_ins"
  yr_boundary_type = "noslip_ins"
  gr_amrexMG_composite_solve = true
  gr_amrexMG_Tol = 1.0e-12
  gr_amrexMG_max_iter = 200
  gr_hyprePrintSolveInfo = false
  gr_hyprePcType = "HYPRE_AMG"
  gr_hypreSolverType = "HYPRE_BICGSTAB"
  gr_hypreRelTol = 1e-12
  gr_hypreFloor = 1e-16
  nblockx = 100
  nblocky = 10
  nrefs = 10000000
  lrefine_min = 1
  lrefine_max = 1
  flux_correct = true

[IncompNS]
  ins_invReynolds = 0.0042
  ins_inflowVelScale = 1.0
  ins_gravY = -1.0
  ins_cflFlg = 1
  ins_cfl = 0.05
  ins_sigma = 0.05
  ins_dtSpec = 0.1e-3
  ins_pressureCorrect = false
  ins_intSchm = 1
  length = 1e-3
  time = 10e-3

[Simulation]
  sim_outletBuffer = 2.0

[Multiphase]
  mph_rhoGas = 0.0083
  mph_muGas = 1.0
  mph_iPropSmear = 1.5
  mph_thcoGas = 0.25
  mph_CpGas = 0.83
  mph_Stefan = 0.5298
  mph_Tsat = 0.15
  mph_invWeber = 1.0

[HeatAD]
  ht_Prandtl = 8.4
  ht_intSchm = 1

[Driver]
  restart = false
  nend = 1200000
  tmax = 1.0
  dtinit = 0.1e-3
  dtmax = 0.4e-3
  tstep_change_factor = 1.01

[IO]
  basenm = "INS_Flow_Boiling_"
  checkpointFileIntervalTime = 1.0
  plotFileIntervalTime = 0.1
  checkpointFileNumber = 0
  rolling_checkpoint = 2
  plotFileNumber = 0
  plot_var_1 = "pres"
  plot_var_2 = "velx"
  plot_var_3 = "vely"
  plot_var_4 = "dfun"
  plot_var_5 = "temp"
  plot_var_6 = "mflx"
  plot_var_7 = "velz"
  ignoreForcedPlot = true
